product_category_list=[["FNKGCN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FNKGCN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FATACN0012.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FBPAAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FBRACN0011","Nhóm hàng hóa 1_TÂN DƯỢC"],
                        ["FBTACN0022","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FENTAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FOMEAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FPHAAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FTHBCN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FVITAA0031","Nhóm hàng hóa 1_TPCN"],
                        ["FXHKAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FBTNAA0011","Nhóm hàng hóa 2_TPCN"],
                        ["FCALAA0013","Nhóm hàng hóa 1_TPCN"],
                        ["FCUMAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FEURAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FGINAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FHHACN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FHHACN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FHHDAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FHNTCN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FHTDCN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FKCNAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FMDGAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FREPCN0041","Nhóm hàng hóa 1_TÂN DƯỢC"],
                        ["FSANAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FTDACN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FTHBCN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FTNHAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FTNHAA0013","Nhóm hàng hóa 1_TPCN"],
                        ["FVADAA0013","Nhóm hàng hóa 1_TPCN"],
                        ["FVITAA0022","Nhóm hàng hóa 1_TPCN"],
                        ["FVNKAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FVXACN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FXHAAA0013","Nhóm hàng hóa 1_TPCN"],
                        ["BMDGAA00210_TV","Nhóm hàng hóa 1_TPCN"],
                        ["FAGAAA0011","Nhóm hàng hóa 2_TPCN"],
                        ["FANXAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FARGAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FATACN0012","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FATACN0021","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FATACN0021.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FBGAAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FBGAAA0013","Nhóm hàng hóa 1_TPCN"],
                        ["FBTACN0022.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FBTACN0023","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FBTACN0023.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FBTNAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FCALAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FCALAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FCANAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FDDXAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FDGAAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FDNDAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FDXAAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FEUPCN0011","Nhóm hàng hóa 1_TÂN DƯỢC"],
                        ["FEURAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FEURAA0022","Nhóm hàng hóa 1_TPCN"],
                        ["FEURAA0031","Nhóm hàng hóa 1_TPCN"],
                        ["FFERAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FFERAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FGCQAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FGCQAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FGDGAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FGLUAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FGOLAA0012","Nhóm hàng hóa 2_TPCN"],
                        ["FGOLAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FHAACN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FHAACN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FHHAAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FHNTCN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FHOMAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FHTDCN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FKDRAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FKIDAA0011","Nhóm hàng hóa 2_TPCN"],
                        ["FKNEAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FKNEAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FKOHAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FKTTAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FKTTAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FLIVAA0011","Nhóm hàng hóa 2_TPCN"],
                        ["FMDGAA0022","Nhóm hàng hóa 1_TPCN"],
                        ["FMDGAA0024","Nhóm hàng hóa 1_TPCN"],
                        ["FNSMAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FOMEAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FREPCN0011","Nhóm hàng hóa 1_TÂN DƯỢC"],
                        ["FSANAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FSILAA0011","Nhóm hàng hóa 2_TPCN"],
                        ["FTDACN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FTKACN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FTKACN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FTNGAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FTNMAA0021","Nhóm hàng hóa 2_TPCN"],
                        ["FTTACN0012","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FTTACN0012.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FVADAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FVEAAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FVEAAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FVITAA0021","Nhóm hàng hóa 1_TPCN"],
                        ["FVKAAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FVKACN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FVKACN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FVNKAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FVTAAA0011","Nhóm hàng hóa 2_TPCN"],
                        ["FVVGCN0011","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FVVGCN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FVXACN0011 T","Nhóm hàng hóa 1_THUỐC DD"],
                        ["FVXACN0011.1","Nhóm hàng hóa 1_THUỐC DD DÁN TEM"],
                        ["FXHAAA0012","Nhóm hàng hóa 1_TPCN"],
                        ["FXMAAA0011","Nhóm hàng hóa 1_TPCN"],
                        ["FXNMAA0011","Nhóm hàng hóa 1_TPCN"]]